server:
  port: 9090

management:
  endpoints.web.exposure.include: health,info

logging:
  level:
    com.workshop.payment: INFO

app:
  payment:
    default-fail-rate: ${DEFAULT_FAIL_RATE:10}  # 0~100 (%)
    error-mode: ${PAYMENT_ERROR_MODE:false}