server:
  port: ${SERVER_PORT:8080}

order:
  service-url: ${ORDER_SERVICE_URL:http://localhost:8081}  # compose와 동일 변수명

management:
  endpoints.web.exposure.include: health,info
  endpoints.enabled-by-default: false
  endpoints.jmx.exposure.include: env,health,info,metrics
  endpoint.info.enabled: true
  endpoint.health.enabled: true
  endpoint.metrics.enabled: true
  endpoint.env.enabled: true
  endpoint.env.show-values: ALWAYS

spring:
  jmx:
    enabled: true
    
logging:
  level:
    com.workshop.gateway: INFO
