server:
  port: ${SERVER_PORT:8080}

management:
  endpoints.web.exposure.include: health,info
  endpoints.enabled-by-default: false
  endpoints.jmx.exposure.include=env,health,info,metrics
  endpoint.info.enabled=true
  endpoint.health.enabled=true
  endpoint.metrics.enabled=true
  endpoint.env.enabled=true
  endpoint.env.show-values=ALWAYS

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:orders}
    username: ${DB_USER:orders}
    password: ${DB_PASS:orderspw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.workshop.order.events,com.workshop.inventory.events,com.workshop.fulfillment.events"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   # 타입헤더 생략(호환성↑)
  jmx:
    enabled: true

app:
  event:
    ns: ${EVENT_NS:orders.v1}
  inventory:
    reserved-topic: ${EVENT_NS:orders.v1}.inventory_reserved
    rejected-topic: ${EVENT_NS:orders.v1}.inventory_rejected
  payment:
    authorized-topic: ${EVENT_NS:orders.v1}.payment_authorized
    failed-topic:     ${EVENT_NS:orders.v1}.payment_failed

payment:
  base-url: ${PAYMENT_BASE_URL:http://localhost:9090}
  error-mode: ${PAYMENT_ERROR_MODE:false}