{{- $global := .Values.global -}}
{{- range $name, $cfg := .Values.apps }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels: { app.kubernetes.io/name: {{ $name }} }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: {{ $name }} }
  template:
    metadata:
      labels: { app.kubernetes.io/name: {{ $name }} }
    spec:
      {{- if $global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ $global.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ $global.imageRegistry }}/{{ $name }}:{{ $global.imageTag }}"
          imagePullPolicy: always
          ports:
            - containerPort: {{ default 8080 $cfg.service.port }}

          {{- if or $cfg.envFromSecrets $cfg.envFromConfigMaps }}
          envFrom:
            {{- range $cfg.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range $cfg.envFromConfigMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          {{- end }}

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ $global.kafkaBootstrap }}"
            {{- range $k, $v := $cfg.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet: { path: /actuator/health, port: {{ default 8080 $cfg.service.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: {{ default 8080 $cfg.service.port }} }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels: { app.kubernetes.io/name: {{ $name }} }
spec:
  type: {{ default "ClusterIP" $cfg.service.type }}
  selector: { app.kubernetes.io/name: {{ $name }} }
  ports:
    - name: http
      port: {{ if eq (default "ClusterIP" $cfg.service.type) "LoadBalancer" }}80{{ else }}{{ default 8080 $cfg.service.port }}{{ end }}
      targetPort: {{ default 8080 $cfg.service.port }}

{{- end }}
