{{- $global := .Values.global -}}
{{- range $name, $cfg := .Values.apps }}
{{- if ne $name "load-generator" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels: { app.kubernetes.io/name: {{ $name }} }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: {{ $name }} }
  template:
    metadata:
      labels: { app.kubernetes.io/name: {{ $name }} }
    spec:
      {{- if $global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ $global.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ $global.imageRegistry }}/{{ $name }}:{{ $global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ default 8080 $cfg.containerPort }}
              name: http

          {{- if or $cfg.envFromSecrets $cfg.envFromConfigMaps }}
          envFrom:
            {{- range $cfg.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range $cfg.envFromConfigMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          {{- end }}

          {{- if $cfg.env }}
          env:
            {{- range $key, $value := $cfg.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- end }}
          readinessProbe:
            httpGet: { path: /actuator/health, port: {{ default 8080 $cfg.containerPort }} }
            initialDelaySeconds: 100
            periodSeconds: 60
          livenessProbe:
            httpGet: { path: /actuator/health, port: {{ default 8080 $cfg.containerPort }} }
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels: { app.kubernetes.io/name: {{ $name }} }
spec:
  type: {{ default "ClusterIP" $cfg.service.type }}
  selector: { app.kubernetes.io/name: {{ $name }} }
  ports:
    - name: http
      port: {{ if eq (default "ClusterIP" $cfg.service.type) "LoadBalancer" }}80{{ else }}{{ default 8080 $cfg.service.port }}{{ end }}
      targetPort: {{ default 8080 $cfg.containerPort }}

{{- end }}
